version: '3.2'

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

services:
  app:
    container_name: "rehau"
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    # image: php:7.2.10-fpm-alpine
    volumes:
      - ./src:/app:rw
    # restart: always
    networks:
      - backend-network
      - frontend-network
    environment:
      CONTAINER_ROLE: app
    command: tail -f /dev/null

  nginx:
    image: nginx:1.15.8-alpine
    restart: always
    environment:
      ROOT_DIR: '/app/dist'
    volumes:
      - ./src:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
    networks:
      - frontend-network
